name: Continuous Integration For the Project
on: 
  push: 
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "project 3/api"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: "project 3/api/package-lock.json"

      - name: Installing dependencies
        run: npm ci
      
      - name: Lint check
        run: npm run lint

